fail_fast: false
exclude: "External/.*"
repos:
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: master
    hooks:
      - id: clang-format
        args: [ --style=Google ]
      - id: cppcheck
        args: ['--suppress=missingInclude','--suppress=missingIncludeSystem', '--suppress=unusedFunction']
