fail_fast: false
exclude: "External/.*"
repos:
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-format
        args: [ --style=Google ]
      - id: cppcheck
<<<<<<< HEAD
        args: ['--suppress=missingInclude', '--suppress=missingIncludeSystem', '--suppress=unusedFunction']
=======
        args: ['--suppress=missingInclude','--suppress=missingIncludeSystem', '--suppress=unusedFunction']
>>>>>>> c6740a3cadf208ebebae8ab07838619b2643662f
